version: "3"

services:
  image_upload:
    container_name: image-upload
    image: paullessing/image-upload:8
    ports:
      - "3000:3000"
    volumes:
      - "./config/config.json:/config.json"
    environment:
      CONFIG_FILE: /config.json
    environment:
      - VIRTUAL_HOST=images.putit.at
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=images.putit.at
      - LETSENCRYPT_EMAIL=lessing.paul@gmail.com
#    links:
#      - db

#  db:
#    image: mongo:3
